Add debug code and userns setup

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -117,6 +117,12 @@ jobs:
         with:
           path: customer-application
 
+      - name: Debug workspace permissions
+        run: |
+            ls -la ${{ github.workspace }}/customer-application/.git
+            stat ${{ github.workspace }}/customer-application/.git/index.lock || echo "index.lock not found"
+
+
       - name: Run container with custom setup
         run: |
             sudo chown -R $(id -u):$(id -g) ${{ github.workspace }}
@@ -124,13 +130,14 @@ jobs:
               --device=/dev/ttyUSB0 \ 
               --privileged \
               --network host \
+              --userns=host \
               -v /var/run/dbus:/var/run/dbus \
               -v /run/dbus:/run/dbus \
               -v /dev:/dev \
               -v ${{ github.workspace }}:/workspace \
               -w /workspace/customer-application \
               -e DBUS_SESSION_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket \
-              --user root \
+              --user $(id -u):$(id -g) \
               ${{ needs.process-image.outputs.image }} 
 
       - name: Set build env variables
