Install python packages in testing.yml

diff --git a/.github/workflows/testing.yml b/.github/workflows/testing.yml
--- a/.github/workflows/testing.yml
+++ b/.github/workflows/testing.yml
@@ -115,14 +115,22 @@ jobs:
             echo "test_tag: ${{ inputs.test_tag }}"
             echo "pytest_args: ${{ inputs.pytest_args }}"
             echo "test_hardware: ${{ inputs.test_hardware }}"'
+
+      # Create Python virtual env and install required packages
+      - name: Install Python extra packages
+        shell: bash
+        run: |
+            docker exec -u $(id -u):$(id -g) -w /workspace/customer-application zephyr-env \
+            bash -c "python3 -m venv .venv || { echo 'Failed to create .venv in customer-application/'; exit 1; }
+            source .venv/bin/activate && \
+            pip install -r requirements-extras.txt"
             
       # Generate list of all tests in application in txt-format
       - name: Create list of all application tests
         shell: bash
         run: |
             docker exec -u $(id -u):$(id -g) -w /workspace/customer-application zephyr-env \
-            bash -c "python3 -m venv .venv || { echo 'Failed to create .venv in customer-application/'; exit 1; }
-            source .venv/bin/activate && \
+            bash -c "source .venv/bin/activate && \
             python .github/scripts/tests_yaml_parser.py"
 
       # Generate tests paths to run with twister command
